director_uuid: deadbeef
instance_groups:
- instances: 1
  jobs:
  - name: foobar
  name: foobar
  networks:
  - name: a
  properties:
    quote:
      "n": "yes"
      "y": "no"
  stemcell: default
  vm_type: a
name: simple
releases:
- name: bosh-release
  version: 0.1-dev
stemcells:
- alias: default
  os: toronto-os
  version: latest
update:
  canaries: 2
  canary_watch_time: 4000
  max_in_flight: 1
  update_watch_time: 20
