script: 'bundle exec rake --trace travis:install_go $TASKS'

before_install: 'sudo apt-get update'
install:
  - 'sudo apt-get install dnsutils'
  - 'bundle install --local --without development'

rvm:
  - ruby-1.9.3
  - ruby-2.1.2

env:
  # limit unit test threads to 1 to avoid SimpleCov race conditions:
  # https://github.com/colszowka/simplecov/issues/305
  - COVERAGE=true BOSH_MAX_THREADS=1 TASKS="spec:unit ci:publish_coverage_report"
  - DB=mysql NUM_GROUPS=4 GROUP=1    TASKS="spec:integration"
  - DB=mysql NUM_GROUPS=4 GROUP=2    TASKS="spec:integration"
  - DB=mysql NUM_GROUPS=4 GROUP=3    TASKS="spec:integration"
  - DB=mysql NUM_GROUPS=4 GROUP=4    TASKS="spec:integration"
  - DB=postgres NUM_GROUPS=4 GROUP=1 TASKS="spec:integration"
  - DB=postgres NUM_GROUPS=4 GROUP=2 TASKS="spec:integration"
  - DB=postgres NUM_GROUPS=4 GROUP=3 TASKS="spec:integration"
  - DB=postgres NUM_GROUPS=4 GROUP=4 TASKS="spec:integration"

addons:
  code_climate:
    # master branch
    repo_token: c5256f87295d0bf77f092dfa5f037b17ef17439c7342209256258084a54e410f
