---
name: create-swap-delete-deployment

releases: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  vm_strategy: 'create-swap-delete'

instance_groups:
- name: csd
  stemcell: default
  vm_type: default
  instances: 2
  networks:
  - {name: default}
  azs: [z1]
  jobs: []
