---
name: test-brats-deployment

releases:
- name: os-conf
  version: 12

stemcells:
- alias: ubuntu_stemcell
  os: ubuntu-trusty
  version: latest

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

instance_groups:
- name: test-brats
  instances: 1
  azs: [z1]
  jobs:
  - name: user_add
    release: os-conf
    properties:
      users: []
  vm_type: default
  stemcell: ubuntu_stemcell
  networks:
  - name: default
