---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/agent

inputs:
- name: bosh-src
- name: version

params: {}

run:
  path: bosh-src/ci/tasks/assert-version-aligns.sh
