---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-src

outputs:
- name: slack-message

run:
  path: bosh-src/ci/tasks/prep-slack-alert.sh
