---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: everlag/bosh-ci-dev # TODO: back to 'bosh/blobstore_client'

inputs:
  - name: bosh-src
run:
  path: bosh-src/ci/tasks/test-gcs-blobstore-client-integration.sh
params:
  google_json_key_data: replace-me
