---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-src
  - name: dns-release
  - name: candidate-warden-ubuntu-stemcell
  - name: bosh-release

params:
  DNS_RELEASE_FILE_PATH: "dns-release/release.tgz"

run:
  path: bosh-src/ci/tasks/test-brats.sh
