---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-src
- name: bosh-cli
- name: bosh-agent

run:
  path: bosh-src/ci/tasks/test-integration-gocli.sh

params:
  RUBY_VERSION:            2.4.4
  DB:                      replace-me
  LOG_LEVEL:               ERROR
  NUM_GROUPS:              8
  GROUP:                   1,2,3,4,5,6,7,8
  SPEC_PATH:               ~
  SHA2_MODE:               ~
  DB_TLS:                  false
  DEFAULT_UPDATE_VM_STRATEGY: "delete-create"
