---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: bosh-src
- name: dav-cli

run:
  path: bosh-src/ci/tasks/test-blobstore-load.sh
