---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-deployment
  - name: stemcell
  - name: bosh-cli

outputs:
  - name: director-state

run:
  path: bosh-src/ci/pipelines/stemcells/tasks/deploy-director.sh
