---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/aws-cpi-release

inputs:
  - name: bosh-src
  - name: version
outputs:
  - name: version-tag

run:
  path: bosh-src/ci/pipelines/stemcells/tasks/publish.sh

params: {}
