---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-deployment
  - name: director-state
  - name: bosh-cli

run:
  path: bosh-src/ci/pipelines/stemcells/tasks/teardown.sh
