---
platform: linux

image: docker:///bosh/integration

inputs:
- name: bosh-src

run:
  path: bosh-src/ci/concourse/tasks/rake.sh
  args: ["--trace", "go", "spec:unit"]

params:
  # defaults for 'fly execute'...
  RUBY_VERSION: 2.1.6
