---
platform: linux

image: docker:///bosh/compiled-release

inputs:
  - name: bosh-src
  - name: stemcell
  - name: uaa-release
  - name: bosh-release
  - name: bosh-aws-cpi-release

outputs:
  - name: compiled-releases

run:
  path: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.sh

params:
  BOSH_TARGET_IP: required
  BOSH_USERNAME: admin
  BOSH_PASSWORD: admin
