---
platform: linux

image: docker:///bosh/compiled-release

inputs:
  - name: uaa-release
  - name: bosh-release
  - name: bosh-aws-cpi-release
  - name: stemcell

outputs:
  - name: compiled-releases

run:
  path: bosh-src/ci/pipelines/compiled-releases/tasks/export-release.sh

params:
  TARGET: required
  USERNAME: required
  PASSWORD: required
