---
groups:
  - name: bosh-google-stemcell
    jobs:
      - build-google-kvm-ubuntu-trusty
      - build-google-kvm-centos-7

jobs:
  - name: build-google-kvm-ubuntu-trusty
    plan:
      - aggregate:
          - get: version
            trigger: true
          - get: bosh-src
          - get: bosh-release
          - get: os-image
            resource: ubuntu-trusty-os-image

      - task: create-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
        privileged: true
        params:
          IAAS:       google
          HYPERVISOR: kvm
          OS_NAME:    ubuntu
          OS_VERSION: trusty

      - task: create-light-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build-light-google.yml
        privileged: true
        params:
          OS_NAME:         ubuntu
          OS_VERSION:      trusty
          BUCKET_NAME:     {{google_stemcells_bucket_name}}

      - aggregate:
        - put: google-kvm-ubuntu-trusty
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz
            predefined_acl: "publicRead"

        - put: google-kvm-ubuntu-trusty-sha1
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz.sha1
            predefined_acl: "publicRead"

        - put: google-kvm-ubuntu-trusty-raw
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz
            predefined_acl: "publicRead"

        - put: light-google-kvm-ubuntu-trusty
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz
            predefined_acl: "publicRead"

        - put: light-google-kvm-ubuntu-trusty-sha1
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz.sha1
            predefined_acl: "publicRead"

  - name: build-google-kvm-centos-7
    plan:
      - aggregate:
          - get: version
            trigger: true
          - get: bosh-src
          - get: bosh-release
          - get: os-image
            resource: centos-7-os-image

      - task: create-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
        privileged: true
        params:
          IAAS:       google
          HYPERVISOR: kvm
          OS_NAME:    centos
          OS_VERSION: 7

      - task: create-light-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build-light-google.yml
        privileged: true
        params:
          OS_NAME:         centos
          OS_VERSION:      7
          BUCKET_NAME:     {{google_stemcells_bucket_name}}

      - aggregate:
        - put: google-kvm-centos-7
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz
            predefined_acl: "publicRead"

        - put: google-kvm-centos-7-sha1
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz.sha1
            predefined_acl: "publicRead"

        - put: google-kvm-centos-7-raw
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent-raw.tar.gz
            predefined_acl: "publicRead"

        - put: light-google-kvm-centos-7
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz
            predefined_acl: "publicRead"

        - put: light-google-kvm-centos-7-sha1
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz.sha1
            predefined_acl: "publicRead"

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/ljfranklin/bosh.git
      branch: google
      # uri: https://github.com/cloudfoundry/bosh.git
      # branch: master

  - name: version
    type: semver
    source:
      driver: s3
      key: bosh-stemcell/version
      bucket: {{stemcell_bucket}}
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  # os-images

  - name: ubuntu-trusty-os-image
    type: s3
    source:
      bucket: {{osimage_bucket}}
      versioned_file: bosh-ubuntu-trusty-os-image.tgz
      access_key_id: {{os_image_aws_access_key}}
      secret_access_key: {{os_image_aws_secret_key}}

  - name: centos-7-os-image
    type: s3
    source:
      bucket: {{osimage_bucket}}
      versioned_file: bosh-centos-7-os-image.tgz
      access_key_id: {{os_image_aws_access_key}}
      secret_access_key: {{os_image_aws_secret_key}}

  # stemcells
  - name: google-kvm-ubuntu-trusty
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz

  - name: google-kvm-ubuntu-trusty-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz.sha1

  - name: google-kvm-ubuntu-trusty-raw
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz

  - name: light-google-kvm-ubuntu-trusty
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz

  - name: light-google-kvm-ubuntu-trusty-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz.sha1

  - name: google-kvm-centos-7
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz

  - name: google-kvm-centos-7-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz.sha1

  - name: google-kvm-centos-7-raw
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent-raw.tar.gz

  - name: light-google-kvm-centos-7
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz

  - name: light-google-kvm-centos-7-sha1
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz.sha1

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
