inherit_from: ../.rubocop.yml

CaseIndentation:
  Enabled: false

DotPosition:
  Enabled: false

LineLength:
  Max: 135

MethodLength:
  CountComments: false
  Max: 31

RescueException:
  Enabled: false

WhileUntilModifier:
  Enabled: false
