---
groups:
  - name: bosh-global-net
    jobs:
    - unit-1.9
    - unit-2.1
    - integration-1.9-postgres
    - integration-2.1-mysql
    - integration-2.1-postgres
    - load-tests

jobs:
  - name: unit-1.9
    public: true
    serial: true
    plan:
    - get: bosh-src
      trigger: true
    - task: test
      file: bosh-src/ci/tasks/test-unit.yml
      config:
        params:
          RUBY_VERSION: 1.9.3

  - name: unit-2.1
    public: true
    serial: true
    plan:
      - get: bosh-src
        trigger: true
      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 2.1.6

  - name: integration-1.9-postgres
    public: true
    serial: true
    plan:
    - get: bosh-src
      passed:
      - unit-1.9
      trigger: true
    - task: test
      privileged: true
      file: bosh-src/ci/tasks/test-integration.yml
      config:
        params:
          DB: postgresql
          RUBY_VERSION: 1.9.3
          NUM_GROUPS: 8

  - name: integration-2.1-mysql
    public: true
    serial: true
    plan:
    - get: bosh-src
      passed:
      - unit-2.1
      trigger: true
    - task: test
      privileged: true
      file: bosh-src/ci/tasks/test-integration.yml
      config:
        params:
          DB: mysql
          RUBY_VERSION: 2.1.6
          NUM_GROUPS: 8

  - name: integration-2.1-postgres
    public: true
    serial: true
    plan:
    - get: bosh-src
      passed:
      - unit-2.1
      trigger: true
    - task: test
      privileged: true
      file: bosh-src/ci/tasks/test-integration.yml
      config:
        params:
          DB: postgresql
          RUBY_VERSION: 2.1.6
          NUM_GROUPS: 8

  - name: load-tests
    public: true
    serial: true
    plan:
    - get: bosh-src
      passed:
      - integration-2.1-postgres
      - integration-2.1-mysql
      - integration-1.9-postgres
    - get: bosh-load-tests
    - task: test
      privileged: true
      file: bosh-load-tests/ci/tasks/test.yml

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: global-net
  - name: bosh-load-tests
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-load-tests
      branch: master
