---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-src
  - name: director-state
  - name: bosh-cli

params:
  BOSH_LOG_LEVEL:         info

run:
  path: bosh-src/ci/pipelines/stemcell/tasks/teardown.sh
